version: '3'
services:
  igame:
    build: .
    ports:
      - "8000:5000"
    env_file: .env
    restart: always
  redis:
    image: "redis:alpine"
  apache:
    image: httpd:2.4
    ports:
      - "80:80"
      - depends_on:
          - web
