"""Test migration.

Revision ID: 1c4b3fb847c1
Revises: 
Create Date: 2023-11-13 11:44:41.871342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4b3fb847c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index('gamesid_idx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index('gamesid_idx', ['game_id'], unique=False)

    # ### end Alembic commands ###
