"""empty message

Revision ID: 43a901e5b9d6
Revises: 46cc80fed0cb
Create Date: 2025-02-10 14:58:01.898234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43a901e5b9d6'
down_revision = '46cc80fed0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_games',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], name=op.f('fk_user_games_game_id_games')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_user_games_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'game_id', name=op.f('pk_user_games'))
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.drop_constraint('games_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('rating')
        batch_op.drop_column('user_id')
        batch_op.drop_column('likes')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False))
        batch_op.create_unique_constraint('users_user_id_key', ['user_id'])
        batch_op.alter_column('created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint('users_id_key', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False))
        batch_op.create_unique_constraint('users_id_key', ['id'])
        batch_op.alter_column('created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('games_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('title')

    op.drop_table('user_games')
    # ### end Alembic commands ###
