"""empty message

Revision ID: 90f4b0e2943e
Revises: 46cc80fed0cb
Create Date: 2025-02-10 15:43:01.873502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90f4b0e2943e'
down_revision = '46cc80fed0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.drop_constraint('games_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('likes')
        batch_op.drop_column('user_id')
        batch_op.drop_column('rating')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('users_user_id_key', ['user_id'])
        batch_op.alter_column('created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint('users_id_key', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.create_unique_constraint('users_id_key', ['id'])
        batch_op.alter_column('created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('likes', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('games_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('title')

    # ### end Alembic commands ###
